import type { Metadata } from "next";
import { Oswald, Raleway, Rozha_One } from "next/font/google";

import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Copyright } from "@/components/copyright";

import "./globals.css";

const oswald = Oswald({
  subsets: ["latin", "cyrillic"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-oswald",
});

const raleway = Raleway({
  subsets: ["latin", "cyrillic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway",
});

const rozha_one = Rozha_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-rozha-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${raleway.variable} ${rozha_one.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
        <Copyright />
      </body>
    </html>
  );
}
